### PR TITLE
Fix HashCheck install location and embed

### PR DESCRIPTION
**Pull request by teknowledgist**
1. This is a post-install fix to a [long-standing installer issue](https://github.com/gurnec/HashCheck/issues/15) where HashCheck installs into the Windows directory and breaks on Win10 feature upgrades.  If HashCheck is ever updated to resolve the issue itself, the extra code shouldn't cause any issues.
2. Embedding the installer (especially for small apps) is more efficient as there is only one download/server and makes it easy to create/maintain a local Chocolatey repository.

Note:  Most of the nuspec changes are just re-arrangements to align the order with the default template.

Thanks for maintaining this package!

### CODE REVIEW

**Comment by Thilas** [comment]
@teknowledgist, thanks for the PR but I would have prefer one per change: the installer embedding and the actual fix.

Anyway, here are some comments on both points:

1. I'm not really found of embedding installers unless I have to for some reasons
2. I would prefer to use `regsvr32` to unreg `HashCheck.dll` from its old location and rereg it in its new location

If you are willing to provide something with only the second point, you are welcome. Otherwise, I'll do it in the coming weeks. Thanks for your help!

**Comment by teknowledgist** [comment]
@Thilas, Of course, it is your package to do with as you wish, but I too have comments:  😄 

1. I have started preferring embedded packages because it lowers the number of failure points of which the user and package maintainer have no control over, and it makes it easy for Chocolatey users who don't have general Internet access (i.e. corporate firewall).  They can use an internal/local repository and don't need to modify the downloaded package.  Notice, [the Chocolatey-CoreTeam is pushing for embedded packages as well.](https://github.com/chocolatey/chocolatey-coreteampackages/issues/866)
2. It has been a while, but I think I recall trying `regsvr32` and encountering an issue (though I don't remember the specifics).  Since I was mucking around in the registry anyway (converting to a machine-install), I guess I figured, I may as well go the whole way.  If I get a chance, I will see if I can get a revised version using `regsvr32` working and push a change to the PR.

Thanks for the comments.

**Comment by teknowledgist** [comment]
I played with the install script to use `regsvr32` and (re)discovered why I didn't use it in the fix...

    regsvr32 /s /i /n "c:\Program Files\HashCheck\HashCheck.dll"

simply re-installs HashCheck to `$env:systemroot\System32\ShellExt\HashCheck.dll` and registers that path in the registry.  The install command in the DLL must have that path hard-coded.  Only directly changing the registry allows the new DLL location to be used for HashCheck functions.

[The docs for `regsvr32.exe`](https://support.microsoft.com/en-us/help/249873/how-to-use-the-regsvr32-tool-and-troubleshoot-regsvr32-error-messages) do show that the `/i` switch has option to run a "cmdline", but I don't know if that means you can call internal .dll functions nor if the HashCheck.dll library has an option for changing the install location that could be called.  That would require digging through the source code and a lot more investigation than I am able to do.

At this point, I think the registry adjustments are the best option for "fixing" the HashCheck install.

**Comment by teknowledgist** [comment]
Since I was adjusting the uninstall registry key anyway, I added a `quietuninstallstring` property.  That property is recognized by the Chocolatey AutomaticUninstaller, which eliminates the need for the `chocolateyuninstall.ps1` file.

**Comment by Thilas** [comment]
@teknowledgist, I pushed a [commit](https://github.com/Thilas/chocolatey-packages/commit/ddfb85bc49bb34658f4c8bc8bf85f22801f54edf) on the master branch that includes some changes compared to your proposition:

- I'm using `regsvr32` to relocate the dlls ; thanks to your help, I figured out that there was actually an easy way to skip the dlls copy (see https://github.com/gurnec/HashCheck/blob/3fa77e0cf5c8b9cdec36f916759ae8ea46076537/HashCheck.cpp#L252)
- I kept the `chocolateyUninstall.ps1` script otherwise WoW64 dll was not fully uninstalled

I'm closing then this PR and thanks again for your contribution.

**Pull request closed without merging**
